# This file can be used to install module depdencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---
fixtures:
  forge_modules:
    apt:
      repo: puppetlabs/apt
      ref: 7.5.0
    concat:
      repo: "puppetlabs/concat"
      ref: "6.2.0"
    puppet_agent:
      repo: "puppetlabs/puppet_agent"
      ref: "4.0.0"
    selinux:
      repo: "puppet/selinux"
      ref: "3.2.0"
    stdlib:
      repo: "puppetlabs/stdlib"
      ref: "6.3.0"
    systemd:
      repo: "camptocamp/systemd"
      ref: "2.9.0"
  repositories:
    lsys:
      repo: https://github.com/aursu/puppet-lsys.git
      ref: tags/v0.5.4
    nginx:
      repo: https://github.com/aursu/puppet-nginx.git
      ref: tags/v2.0.1-rc0.3
    puppet:
      repo: https://github.com/aursu/puppet-puppet.git
    selinux_core:
      repo: https://github.com/puppetlabs/puppetlabs-selinux_core.git
      puppet_version: ">= 6.0.0"
    tlsinfo:
      repo: https://github.com/aursu/puppet-tlsinfo.git
    yumrepo_core:
      repo: https://github.com/puppetlabs/puppetlabs-yumrepo_core.git
      puppet_version: ">= 6.0.0"
